services:
  oc:
    image: ${IMAGE_PREFIX:-docker.io}/agent/oc-python:3.13
    environment:
      OPENCODE_DISABLE_MODELS_FETCH: true
      OPENCODE_DISABLE_AUTOUPDATE: true
      NPM_CONFIG_REGISTRY: https://registry.npmmirror.com
      # API_BASE_URL: https://api.openai.com/v1
      # API_KEY: sk-xxxxxxxxx
      # HTTP_PROXY: http://127.0.0.1:8080
      # HTTPS_PROXY: http://127.0.0.1:8080
    entrypoint:
      - opencode
      - run
